version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"


sphinx:
  configuration: docs/source/conf.py

# Dependencies required to build your docs
python:
  install:
    - requirements: docs/source/requirements.txt