# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Mujoco
        env:
          MUJOCO_KEY: ${{ secrets.MUJOCO_KEY }}
        run: |
          sudo apt-get update
          sudo apt install -y  libosmesa6-dev  libglew-dev  libgl1-mesa-glx libgl1-mesa-dev libgl1-mesa-glx libglfw3
          sudo apt install xpra xserver-xorg-dev
          
          wget https://www.roboti.us/download/mujoco200_linux.zip
          wget https://mujoco.org/download/mujoco210-linux-x86_64.tar.gz

          mkdir -p "/home/runner/.mujoco/mujoco200"
          mkdir -p "/home/runner/.mujoco/mujoco210"
          
          unzip -o mujoco200_linux.zip -d .
          gzip mujoco210_linux.gz -d
          
          mv mujoco200_linux /home/runner/.mujoco/
          mv mujoco210_linux /home/runner/.mujoco/
          
          cp -r /home/runner/.mujoco/mujoco200_linux/* /home/runner/.mujoco/mujoco200
          cp -r /home/runner/.mujoco/mujoco210_linux/* /home/runner/.mujoco/mujoco210
          
          rm -rf /home/runner/.mujoco/mujoco200_linux
          
          echo  "$MUJOCO_KEY" > "/home/runner/.mujoco/mjkey.txt"

      - name: Install dependencies
        run: |
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/runner/.mujoco/mujoco200/bin
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          pip install -e .
          pip install -e ".[test]"
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.mujoco/mujoco200/bin
          export MUJOCO_KEY_PATH=$HOME/.mujoco/mjkey.txt
          pytest -v
